### ISSUE TITLE
ConcentrationLamp.py Indentation Error

### ISSUE THREAD

**Issue by mhamilt** [luvianmoon/Wanting#1]
# Indentation Error

The indentation error you’re getting looks like it stems from `line 65`. Be careful of the white space.

# Countratenumber Reset

For some reason you have chosen overwrite the `speech_count` variable with `countratenumber`. You haven’t changed `line 82` To match, so the number never resets.

I would look into the [modulo operator](
https://python-reference.readthedocs.io/en/latest/docs/operators/modulus.html) `%` for this kind of operation.

**Comment by luvianmoon** [comment]
The indentation error was solved and it's not because of the marge of tab and space,It's because the one if statement hadn't been change into comment while others had been change. This made python think the sentence was not finish which lead to an error. The speech_count is use for to count how many voice was detected, it did provide help to understand whether there was problem with the sensor, but evidences showed that it just because the system cannot handle too much information exchange in a millisecond. Since the pi will print "1" or "0" in one millisecond, I create the "countratenumber" and set the threshold as "1000" which means every one sec it will send information to the Philips Hue and control the light. Because 1 sec is still short, the difference between 1 s and 1ms are insignificant but it reduce a lot of work for the machine. After adding the if statement, the problem was solved and the code works really well.
